package com.oyzy.musicservice.dao;

import com.oyzy.musicservice.pojo.Master;
import org.springframework.stereotype.Repository;

@Repository
public interface MasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master
     *
     * @mbg.generated
     */
    int insert(Master record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master
     *
     * @mbg.generated
     */
    int insertSelective(Master record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master
     *
     * @mbg.generated
     */
    Master selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Master record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Master record);

    int verifyPassword(String username, String password);

    int findMaster(String username, String password);
}