package com.oyzy.musicservice.dao;

import com.oyzy.musicservice.pojo.SingerInSong;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SingerInSongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singer_song
     *
     * @mbg.generated
     */
    int insert(SingerInSong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singer_song
     *
     * @mbg.generated
     */
    int insertSelective(SingerInSong record);

    List<Integer> selectByUserId(int UserId);


    int deleteBySongid(Integer songid);

    int deleteByuserid(Integer userid);
}