package com.oyzy.musicservice.dao;

import com.oyzy.musicservice.pojo.Song;
import com.oyzy.musicservice.pojo.User;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer songId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated
     */
    int insert(Song record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated
     */
    int insertSelective(Song record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated
     */
    Song selectByPrimaryKey(Integer songId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Song record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Song record);


    int updateSongImg(Song song);
    int updateSongUrl(Song song);

    List<Song> selectByName(String name);
    List<Song> allSong();

    List<Song> selectByUserId(int userId);
}