package com.oyzy.musicservice.dao;

import com.oyzy.musicservice.pojo.UserInList;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UserInListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_list
     *
     * @mbg.generated
     */
    int insert(UserInList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_list
     *
     * @mbg.generated
     */
    int insertSelective(UserInList record);

    List<Integer> selectByUserId(int UserId);

    int deleteBySongListid(Integer listid);

    int deleteByuserid(Integer userid);

}